// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OWic4C8rEshzrPd0X9J2zTcyL_KhhS4',
    appId: '1:683434123196:web:653f2b305a02da234d55b9',
    messagingSenderId: '683434123196',
    projectId: 'lep-chat',
    authDomain: 'lep-chat.firebaseapp.com',
    storageBucket: 'lep-chat.firebasestorage.app',
    measurementId: 'G-L481KKVQ15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTKR4UyWXgZbJrLQycW3TSwck9L-yM4U',
    appId: '1:683434123196:android:efd132b9f52eab524d55b9',
    messagingSenderId: '683434123196',
    projectId: 'lep-chat',
    storageBucket: 'lep-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk68RLtxdNyqsssghgjXxlXzUx5DbiZns',
    appId: '1:683434123196:ios:c13ca1c10ed5419f4d55b9',
    messagingSenderId: '683434123196',
    projectId: 'lep-chat',
    storageBucket: 'lep-chat.firebasestorage.app',
    iosBundleId: 'com.example.leapChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk68RLtxdNyqsssghgjXxlXzUx5DbiZns',
    appId: '1:683434123196:ios:c13ca1c10ed5419f4d55b9',
    messagingSenderId: '683434123196',
    projectId: 'lep-chat',
    storageBucket: 'lep-chat.firebasestorage.app',
    iosBundleId: 'com.example.leapChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8OWic4C8rEshzrPd0X9J2zTcyL_KhhS4',
    appId: '1:683434123196:web:19f162f695fd22654d55b9',
    messagingSenderId: '683434123196',
    projectId: 'lep-chat',
    authDomain: 'lep-chat.firebaseapp.com',
    storageBucket: 'lep-chat.firebasestorage.app',
    measurementId: 'G-D3E7C46LL7',
  );
}
